// errorcodes
INVALID_TOKEN = 0
NICKNAME_ALREADY_IN_USE = 1
GAME_WITH_NAME_ALREADY_RUNNING = 2

// units
UNIT_TYPE_COUNT = 1
UNIT_SOLDIER = 0

// buildings
BUILDING_CASTLE = 0
BUILDING_SPAWNER = 1

// traps
TRAP_PITFALL = 0
TRAP_SPIKE = 1
TRAP_CATAPULT = 2
TRAP_LOOT = 3
