// errorcodes
INVALID_TOKEN = 0
NICKNAME_ALREADY_IN_USE = 1
GAME_WITH_NAME_ALREADY_RUNNING = 2

// units
UNIT_TYPE_COUNT = 7
UNIT_SOLDIER = 0
UNIT_JUMPER = 1
UNIT_RUNNER = 2
UNIT_TANK = 3
UNIT_CROOKEDSOLDIER = 4
UNIT_TOPSTEPSOLDIER = 5
UNIT_BOTTOMSTEPSOLDIER = 6

// buildings
BUILDING_CASTLE = 0
BUILDING_SPAWNER = 1

// traps
TRAP_PITFALL = 0
TRAP_SPIKE = 1
TRAP_CATAPULT = 2
TRAP_LOOT = 3
